In [9]:
import numpy as np
import pandas as pd
from sklearn import preprocessing as pp

 

In [2]:
df = pd.read_csv("/home/sandeep/Desktop/scikit-practice/data/000_example.csv")

In [5]:
group = df['Group'].values

In [7]:
features = df[['F1', 'F2', 'F3']].values

In [15]:
features = features.astype(float)

In [17]:
pp.scale(features)

array([[ 2.44948974,  0.8660254 ,  1.15470054],
       [-0.40824829,  0.8660254 , -0.8660254 ],
       [-0.40824829, -1.15470054, -0.8660254 ],
       [-0.40824829, -1.15470054, -0.8660254 ],
       [-0.40824829,  0.8660254 , -0.8660254 ],
       [-0.40824829,  0.8660254 ,  1.15470054],
       [-0.40824829, -1.15470054,  1.15470054]])

In [24]:
measurements = [
     {'city': 'Dubai', 'temperature': 33.},
     {'city': 'London', 'temperature': 12.},
     {'city': 'San Fransisco', 'temperature': 18.},
 ]

In [19]:
measurements

[{'city': 'Dubai', 'temperature': 33.0},
 {'city': 'Dubai', 'temperature': 12.0},
 {'city': 'San Fransisco', 'temperature': 18.0}]

In [20]:
from sklearn.feature_extraction import DictVectorizer as dv

In [21]:
vec = dv()

In [25]:
vec.fit_transform(measurements).toarray()

array([[ 1.,  0.,  0., 33.],
       [ 0.,  1.,  0., 12.],
       [ 0.,  0.,  1., 18.]])

In [26]:
vec.get_feature_names()

['city=Dubai', 'city=London', 'city=San Fransisco', 'temperature']

In [27]:
from sklearn.naive_bayes import BernoulliNB as nb

In [29]:
clf = nb()

In [31]:
clf.fit(features, group)

BernoulliNB()

In [32]:
nb(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

BernoulliNB()

In [33]:
print(clf.predict(features))

[1 0 0 0 0 1 1]


In [34]:
print(clf.predict_proba(features))

[[0.1394148  0.8605852 ]
 [0.72160356 0.27839644]
 [0.63343109 0.36656891]
 [0.63343109 0.36656891]
 [0.72160356 0.27839644]
 [0.24471299 0.75528701]
 [0.17763158 0.82236842]]


In [35]:
X = np.random.randint(5, size=(6, 3))
y = np.array([1, 2, 3, 4, 5, 6])


In [36]:
from sklearn.naive_bayes import MultinomialNB as mnb

In [37]:
clf1 = mnb()

In [38]:
clf1.fit(X, y)

MultinomialNB()

In [39]:
mnb(alpha=1.0, class_prior=None, fit_prior=True)

MultinomialNB()

In [40]:
print(clf1.predict_proba(X))

[[0.28321262 0.20622913 0.13772004 0.0619386  0.02121699 0.28968262]
 [0.22505776 0.29134588 0.12629661 0.14766039 0.02775357 0.1818858 ]
 [0.13274279 0.12888046 0.31557721 0.10322079 0.1988896  0.12068916]
 [0.08331247 0.15798513 0.15255942 0.29992489 0.24380421 0.06241388]
 [0.03286506 0.06647669 0.17507366 0.18930277 0.51293746 0.02334435]
 [0.27080419 0.184869   0.15214774 0.06580542 0.034235   0.29213866]]


In [43]:
XX = np.random.randint(5, size=(6, 3))
yy = np.array([1, 2, 3, 4, 5, 6])
clf1.partial_fit(XX,yy)

MultinomialNB()

In [44]:
print(clf.predict_proba(X))

[[0.09890427 0.90109573]
 [0.09890427 0.90109573]
 [0.09890427 0.90109573]
 [0.09890427 0.90109573]
 [0.52326468 0.47673532]
 [0.09890427 0.90109573]]
